dist: jammy
language: node_js
node_js:
  - 18
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-4.8
